pipeline {
    agent any 
    tools {
        maven :"MAVEN"
       }
    stages {
        stage("Clean and Package") { 
            steps {
                // Run Maven on a Unix agent.
                sh "mvn clean package"
            }
        }
    }
}